name: untitled
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_messaging: ^16.0.1
  firebase_storage: ^13.0.1
  firebase_analytics: ^12.0.1

  # UI / utils
  image_picker: ^1.2.0
  intl: ^0.20.2
  emoji_picker_flutter: ^4.3.0
  connectivity_plus: ^7.0.0
  cached_network_image: ^3.3.1
  any_link_preview: ^3.0.1
  url_launcher: ^6.3.0
  file_picker: ^10.3.3
  mime: ^2.0.0

  # Аудио/голосовые
  record: ^6.1.2
  just_audio: ^0.10.5
  audio_session: ^0.2.2
  path_provider: ^2.1.4
  wakelock_plus: ^1.2.6

  # WebRTC
  flutter_webrtc: ^0.12.0
  permission_handler: ^11.3.1

  # Сжатие фото (если используешь)
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/ring.mp3


